testSite/myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'

urlpatterns = [
    # http://127.0.0.1:8000/myapp/items/
    path('', views.items),

    # http://127.0.0.1:8000/myapp/items/<my_id>/
    path('items_<int:my_id>/', views.details_id, name='item')     # 3-ий параметр - позволяет гибко
    # изменять название пути до страниц (в index.html: <a href="{% url 'detailItem' item.id %}">)
]

testSite/testSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    # http://127.0.0.1:8000/admin/
    path('admin/', admin.site.urls),

    # http://127.0.0.1:8000/myapp/
    path('myapp/', include('myapp.urls', namespace='myapp'))
]
# Добавляем url с media/
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testSite/myapp/models.py
from django.db.models import Model, CharField, IntegerField, ImageField


# Создаем класс Product для таблицы Product в бд Sqlite3
class Product(Model):
    name = CharField(max_length=100)
    price = IntegerField()
    description = CharField(max_length=200)
    images = ImageField(blank=True)

    # Вместо product object будет выдавать название по полю name таблицы Product (история добавления товаров
    # в панеле admin)
    def __str__(self) -> CharField:
        return self.name

testSite/myapp/views.py
from django.shortcuts import render     # для рендеринга шаблона html-страницы
from django.http import HttpResponse
from .models import Product


def items(requests) -> render:
    items = Product.objects.all()
    context = {
        'items': items
    }
    return render(request=requests, template_name='myapp/index.html', context=context)


# Рендеринг myapps/details.html - обращение по id к товару
def details_id(request, my_id: int) -> render:
    # Используем поле id из таблицы данных Product
    item = Product.objects.get(id=my_id)
    context = {
        'item': item
    }
    return render(request=request, template_name='myapp/details.html', context=context)

testSite/myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}       <!--Позволяет импортировать base.html в другие файлы html-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
</head>
<body>
    {% include "myapp/navbar.html" %}

    {% block content %}
    <!--То, что внутри block content будет уникальным конкретно для этой стр-цы (не будет импортироваться на другие стр-цы)-->
    {% endblock content %}
</body>
</html>

testSite/myapp/templates/myapp/details.html
<!DOCTYPE html>
{% extends "myapp/base.html" %}  <!--Импорт стилей из base.html-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>
    {% block content %}
    <h1>
        This is detail page for: {{ item.name }}, price: {{ item.price }} RUB
    </h1>
    {% endblock content %}
</body>
</html>

testSite/myapp/templates/myapp/index.html
<!DOCTYPE html>
{% extends "myapp/base.html" %}     <!--Импорт стилей из base.html-->
{% block content %}
<main class="mt-10 mx-auto mx-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
    <div class="sm:text-center lg:text-left">
        <h1 class="text-4xl font-extrabold text-gray-900 sm:text-5xl md:text-5xl ml-8">
            <span class="block xl:inline">Популярные Смартфоны</span>
            <span class="block xl:inline text-green-800">По доступным ценам</span>
        </h1>
        <h4 class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0 ml-8">Вы можете заказать товар по всей России</h4>
    </div>


    <div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-col-3 lg:grid-col-3 gap-5">
    {% for item in items %}
    <!--Используем относительные переменные пути detailItem = myapp/items/-->
    <a href="{% url 'myapp:item' item.id %}" class="text-blue-800 font-semibold">
        <div class="rounded overflow-hidden shadow-lg">
            <img class="w-full h-[400px] object-cover" src="{{item.images.url}}">
            <div class="px-6 py-4">
                <p class="font-bold text-xl mb-2">{{item.name}}</p>
                <p class="font-bold text-xl text-black mb-2">RUB {{item.price}}</p>
                <p class="text-gray-700 text-base">{{item.description}}</p>
            </div>
        </div>
    </a>
    {% endfor %}
</div>
</main>


{% endblock content %}
<!--Нужно для импорта base.html-->

testSite/myapp/templates/myapp/navbar.html
{% load static %}       <!--Позволяет импортировать base.html в другие файлы html-->
    <nav class="bg-white shadow-lg">
        <div class="max-w-6x1 mx-auto px-4">
            <div class="flex justify-between">
                <div class="flex space-x-7">
                    <div class="items-center flex space-x-1">
                        <a href="#" class="flex items-center px-2 py-2">
                        <img class="h-8 w-8 bg-white" src="{% static 'myapp/images/logo_shop.png' %}" alt="shop-logo">
                        <span class="text-gray-500 text-xl font-bold">Shop</span>
                        </a>
                    </div>
                    <div class="items-center flex space-x-1">
                        <a href="#" class="py-4 px-2 text-gray-500 text-xl font-bold border-b-4 border-gray-500">Home</a>
                        <a href="#" class="py-4 px-2 text-gray-500 text-xl font-bold">About</a>
                        <a href="#" class="py-4 px-2 text-gray-500 text-xl font-bold">Contacts</a>
                    </div>
                </div>
            </div>
        </div>
    </nav>